services:
  db:
    image: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datawarehouse
    ports:
      - '5432:5432'
volumes:
  pgdata:
